# Need dummy action here as otherwise HA will throw an error :-(
# https://community.home-assistant.io/t/solved-automation-in-package-not-working/24768
- action: []
  id: DUMMY
  alias: DUMMY Can Be Deleted After First Automation Has Been Added
  condition: []
  trigger: []
