# General

homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor

logger:
  default: critical
  logs:
    homeassistant.config: error
    homeassistant.components.zha: debug
    homeassistant.components.light.zha: debug
    zigpy: debug
    zigpy_xbee: debug

history:
recorder:
  purge_keep_days: 60
history_graph: !include history_graph.yaml

frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:


# Track the sun
sun:

# KWB Pelletheizung
modbus:
  type: tcp
  host: 192.168.0.37
  port: 502

# zha:
#   radio_type: xbee
#   usb_path: /dev/ttyUSB0
#   baudrate: 9600
#   database_path: zigbee.db
