# General

homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  packages: !include_dir_named packages
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

system_health:

logger:
  default: warning
  logs:
    homeassistant.components.cover: error
    homeassistant.components.media_player: error
    homeassistant.components.python_script: debug
    homeassistant.components.python_script.covers_ensure_state.py: info
    homeassistant.components.python_script.force_state_updates.py: info
    homeassistant.components.sensor: error
    homeassistant.config: warning
    homeassistant.helpers.entity: error


frontend:

# Enables configuration UI
config:

http:
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

# Mobile apps
mobile_app:

# Track the sun
sun:

python_script:
