# General

homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  packages: !include_dir_named packages
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

logger:
  default: warning
  logs:
    homeassistant.config: warning
    homeassistant.components.zha: debug
    custom_components.cover.zha: info
    zigpy: info
    zigpy.zcl: info
    zigpy_xbee: info


history:
  exclude:
    entities:
      - sensor.heizung_sw_version_minor

recorder:
  purge_keep_days: 60
  exclude:
    entities:
      - sensor.heizung_sw_version_major

history_graph: !include history_graph.yaml

frontend:

# Enables configuration UI
config:

http: !include http.yaml

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.wettersensor

# Enables a map showing the location of tracked devices
map:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:


# Track the sun
sun:

zha: !include zha.yaml
