# General

homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  packages: !include_dir_named packages
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

logger:
  default: warning
  logs:
    homeassistant.components.cover: error
    homeassistant.components.media_player: error
    homeassistant.components.python_script: debug
    homeassistant.components.python_script.covers_ensure_state.py: info
    homeassistant.components.sensor: error
    homeassistant.components.zha: debug
    homeassistant.config: warning
    homeassistant.helpers.entity: error
    custom_components.cover.zha: info
    zigpy: info
    zigpy.zcl: info
    zigpy_xbee: info
    # zigpy_xbee.zigbee.application: debug


history:

recorder:
  purge_keep_days: 60
  exclude:
    entities:
      - sensor.date
      - sensor.power_4
      - sensor.sunprot_eastface_radlevel_temp_mean
      - sensor.sunprot_southface_radlevel_temp_mean
      - sensor.sunprot_westface_radlevel_temp_mean
      - sensor.time
      - sensor.ubisys_d1r_5603_00001d41_4_2820
      - sensor.ubisys_j1_5502_00000dba_3_2820
      - sensor.ubisys_j1_5502_00000dc6_3_2820
      - sensor.ubisys_j1_5502_00000dec_3_2820
      - sensor.ubisys_j1_5502_00000ded_3_2820
      - sensor.ubisys_j1_5502_00000df3_3_2820
      - sensor.ubisys_j1_5502_00001110_3_2820
      - sensor.ubisys_j1_5502_0000240d_3_2820
      - sensor.ubisys_j1_5502_00002415_3_2820
      - sensor.ubisys_j1_5502_0000243d_3_2820
      - sensor.ubisys_j1_5502_0000243e_3_2820
      - sensor.ubisys_j1_5502_000024aa_3_2820
      - sensor.ubisys_j1_5502_000024db_3_2820
      - sensor.ubisys_j1_5502_0000255e_3_2820
      - sensor.ubisys_j1_5502_00002c8c_3_2820
      - sensor.ubisys_j1_5502_00002cc0_3_2820
      - sensor.ubisys_j1_5502_00002cec_3_2820
      - sensor.ubisys_s1_5501_00001a89_3_2820
      - sensor.ubisys_s1_5501_00001a95_3_2820
      - sensor.wettersensor
      - sun.sun

history_graph: !include history_graph.yaml

frontend:

# Enables configuration UI
config:

http: !include http.yaml

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:


# Track the sun
sun:

zha: !include zha.yaml

python_script:
