- platform: yr

- platform: rest
  name: Wettersensor
  resource: http://192.168.0.11/
  json_attributes:
    - readingAgeMs
    - temperatureC
    - sunEastKlx
    - sunSouthKlx
    - sunWestKlx
    - daylightLx
    - isDark
    - windSpeedMs
    - windSpeedGustsMs
    - isRaining
  scan_interval: 60
- platform: template
  sensors:
    wettersensor_reading_age:
      value_template: '{{ states.sensor.wettersensor.attributes["readingAgeMs"] }}'
      unit_of_measurement: "ms"
    wettersensor_temperature:
      value_template: '{{ states.sensor.wettersensor.attributes["temperatureC"] }}'
      unit_of_measurement: "°C"
    wettersensor_sun_east:
      value_template: '{{ states.sensor.wettersensor.attributes["sunEastKlx"] }}'
      unit_of_measurement: "klx"
    wettersensor_sun_south:
      value_template: '{{ states.sensor.wettersensor.attributes["sunSouthKlx"] }}'
      unit_of_measurement: "klx"
    wettersensor_sun_west:
      value_template: '{{ states.sensor.wettersensor.attributes["sunWestKlx"] }}'
      unit_of_measurement: "klx"
    wettersensor_daylight:
      value_template: '{{ states.sensor.wettersensor.attributes["daylightLx"] }}'
      unit_of_measurement: "lx"
    wettersensor_is_dark:
      value_template: '{{ states.sensor.wettersensor.attributes["isDark"] }}'
    wettersensor_wind_speed:
      value_template: '{{ (states.sensor.wettersensor.attributes["windSpeedMs"] | float * 3.6) | int }}'
      unit_of_measurement: "km/h"
    wettersensor_wind_speed_gusts:
      value_template: '{{ (states.sensor.wettersensor.attributes["windSpeedGustsMs"] | float * 3.6) | int }}'
      unit_of_measurement: "km/h"
    wettersensor_is_raining:
      value_template: '{{ states.sensor.wettersensor.attributes["isRaining"] }}'
