input_boolean:

  sunprotection_required_east:
    name: Sonnenschutz nötig Ostseite
    icon: mdi:weather-sunny

  sunprotection_required_south:
    name: Sonnenschutz nötig Südseite
    icon: mdi:weather-sunny

  sunprotection_required_west:
    name: Sonnenschutz nötig Westseite
    icon: mdi:weather-sunny


automation:

  - alias: sunprotection_required_east_on
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_sun_east, above: 80, for: { minutes: 30 } }
    action: { service: input_boolean.turn_on, data: { entity_id: input_boolean.sunprotection_required_east } }
  - alias: sunprotection_required_east_off
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_sun_east, below: 80, for: { minutes: 30 } }
    action: { service: input_boolean.turn_off, data: { entity_id: input_boolean.sunprotection_required_east } }

  - alias: sunprotection_required_south_on
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_sun_south, above: 80, for: { minutes: 30 } }
    action: { service: input_boolean.turn_on, data: { entity_id: input_boolean.sunprotection_required_south } }
  - alias: sunprotection_required_south_off
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_sun_south, below: 80, for: { minutes: 30 } }
    action: { service: input_boolean.turn_off, data: { entity_id: input_boolean.sunprotection_required_south } }

  - alias: sunprotection_required_west_on
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_sun_west, above: 80, for: { minutes: 30 } }
    action: { service: input_boolean.turn_on, data: { entity_id: input_boolean.sunprotection_required_west } }
  - alias: sunprotection_required_west_off
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_sun_west, below: 80, for: { minutes: 30 } }
    action: { service: input_boolean.turn_off, data: { entity_id: input_boolean.sunprotection_required_west } }


  - alias: sunprotection_east_turn_on
    trigger:
      - { platform: state, entity_id: input_boolean.sunprotection_required_east, to: 'on' }
      - { platform: time, minutes: /30, seconds: 0 }
    condition:
      - { condition: state, entity_id: input_boolean.sunprotection_required_east, state: 'on' }
      - { condition: time, after: '08:00:00', before: '19:00:00' }
    action:
      - service: script.sunprotection_east_set
        data: { target_lift: 20, target_tilt: 50 }

  - alias: sunprotection_east_turn_off
    trigger:
      - { platform: state, entity_id: input_boolean.sunprotection_required_east, to: 'off' }
      - { platform: time, minutes: /30, seconds: 0 }
    condition:
      - { condition: state, entity_id: input_boolean.sunprotection_required_east, state: 'off' }
      - { condition: time, after: '08:00:00', before: '19:00:00' }
    action:
      - service: script.sunprotection_east_set
        data: { target_lift: 100, target_tilt: 50 }


script:

  sunprotection_east_set:
    sequence:
    - service: logbook.log
      data_template: { name: "", message: "", errormessage: "*** SUNPROTECTION_EAST_SET *** Started with target_tilt: {{ target_tilt }}, target_lift: {{ target_lift }} ***" }
    # - wait_template: "{{ is_state(script.covers_ensure_state, 'off') }}"
    - service: script.covers_ensure_state
      data_template: { target_lift: "{{ target_lift }}", target_tilt: "{{ target_tilt }}", cover_id: cover.ubisys_j1_5502_00002415_1 }
    - delay: '00:00:10'
    - service: script.covers_ensure_state
      data_template: { target_lift: "{{ target_lift }}", target_tilt: "{{ target_tilt }}", cover_id: cover.ubisys_j1_5502_00002cc0_1 }
    - delay: '00:00:10'
    - service: script.covers_ensure_state
      data_template: { target_lift: "{{ target_lift }}", target_tilt: "{{ target_tilt }}", cover_id: cover.ubisys_j1_5502_0000240d_1 }


history_graph:

  sonnenschutz:
    name: Sonnenschutz
    entities:
      - sensor.wettersensor_temperature
      - sensor.wettersensor_sun_east
      - input_boolean.sunprotection_required_east
      - cover.ubisys_j1_5502_00002415_1
      - cover.ubisys_j1_5502_00002cc0_1
      - cover.ubisys_j1_5502_0000240d_1
      - sensor.wettersensor_sun_south
      - input_boolean.sunprotection_required_south
      - sensor.wettersensor_sun_west
      - input_boolean.sunprotection_required_west
    hours_to_show: 72
    refresh: 60
