automation:

  - alias: covers_down_at_dusk
    trigger:
      - platform: numeric_state
        entity_id: sensor.wettersensor_daylight
        below: '500'
        for:
          minutes: 10
      - platform: time
        minutes: /30
        seconds: 0
    condition:
      - condition: numeric_state
        entity_id: sensor.wettersensor_daylight
        below: '500'
      - condition: time
        after: '17:00:00'
        before: '04:00:00'
    action:
      - service: python_script.covers_ensure_state
        data: { "face": "east", "target_state": "nighttime" }
      - service: python_script.covers_ensure_state
        data: { "face": "south", "target_state": "nighttime" }
      - service: python_script.covers_ensure_state
        data: { "face": "west", "target_state": "nighttime" }

  - alias: covers_up_in_the_morning
    trigger:
      platform: time
      at: '07:30:00'
    action:
      - delay: '00:{{ (range(0, 59)|random|int) }}:00'
      - service: python_script.covers_ensure_state
        data: { "face": "east", "target_state": "morning" }
      - service: python_script.covers_ensure_state
        data: { "face": "south", "target_state": "morning" }
      - service: python_script.covers_ensure_state
        data: { "face": "west", "target_state": "morning" }

  - alias: covers_up_during_daytime
    initial_state: false
    trigger:
      platform: time
      minutes: /30
      seconds: 0
    condition:
      - condition: time
        after: '08:45:00'
        before: '14:00:00'
    action:
      - service: python_script.covers_ensure_state
        data: { "face": "east", "target_state": "morning" }
      - service: python_script.covers_ensure_state
        data: { "face": "south", "target_state": "morning" }
      - service: python_script.covers_ensure_state
        data: { "face": "west", "target_state": "morning" }


homeassistant:

  customize:

    automation.covers_down_at_dusk:
      friendly_name: Raffstore abends runter
    automation.covers_up_in_the_morning:
      friendly_name: Raffstore morgens rauf
    automation.covers_up_during_daytime:
      friendly_name: Raffstore tagsüber oben halten
