input_boolean:
  coverprot_wind_active:
  coverprot_rain_active:

timer:
  coverprot_off_reset:
    duration: '01:00:00'


automation:

  - alias: coverprot_wind_active_on
    trigger: { platform: numeric_state, entity_id: sensor.esp_weathersensor_multisensor_gusts, above: 30 }
    action: { service: input_boolean.turn_on, data: { entity_id: input_boolean.coverprot_wind_active } }
  - alias: coverprot_wind_active_off
    trigger: { platform: numeric_state, entity_id: sensor.esp_weathersensor_multisensor_gusts, below: 25, for: { minutes: 10 } }
    action: { service: input_boolean.turn_off, data: { entity_id: input_boolean.coverprot_wind_active } }

  - alias: coverprot_rain_active_on
    trigger: { platform: state, entity_id: binary_sensor.esp_weathersensor_multisensor_rain, to: 'on' }
    action: { service: input_boolean.turn_on, data: { entity_id: input_boolean.coverprot_rain_active } }
  - alias: coverprot_rain_active_off
    trigger: { platform: state, entity_id: binary_sensor.esp_weathersensor_multisensor_rain, to: 'off' }
    action: { service: input_boolean.turn_off, data: { entity_id: input_boolean.coverprot_rain_active } }

  - alias: coverprot_wind_execute
    trigger:
      - { platform: state, entity_id: input_boolean.coverprot_wind_active, to: 'on' }
      - { platform: time_pattern, minutes: /2, seconds: 0 }
    condition:
      - { condition: state, entity_id: input_boolean.coverprot_wind_active, state: 'on' }
    action:
      - service: cover.open_cover
        entity_id: cover.f1_cov_terrasse_markise_cover
      - service: cover.open_cover
        entity_id: cover.f1_cov_wintergarten_markise_cover
      - service: cover.open_cover
        entity_id: cover.f3_cov_dachfenster_gross_cover

  - alias: coverprot_rain_execute
    trigger:
      - { platform: state, entity_id: input_boolean.coverprot_rain_active, to: 'on' }
      - { platform: time_pattern, minutes: /2, seconds: 0 }
    condition:
      - { condition: state, entity_id: input_boolean.coverprot_rain_active, state: 'on' }
    action:
      - service: cover.open_cover
        entity_id: cover.f1_cov_terrasse_markise_cover
      - service: cover.open_cover
        entity_id: cover.f1_cov_wintergarten_markise_cover
      # f3_cov_dachfenster_gross_cover dient auch der Verdunkelung und bleibt bei Regen draußen.

  - alias: coverprot_off_timer_start
    trigger: {platform: state, entity_id: group.coverprot_automations, to: 'off'}
    action: {service: timer.start, data: {entity_id: timer.coverprot_off_reset}}
  - alias: coverprot_off_timer_cancel
    trigger: {platform: state, entity_id: group.coverprot_automations, to: 'on'}
    action: {service: timer.cancel, data: {entity_id: timer.coverprot_off_reset}}
  - alias: coverprot_off_timer_expired
    trigger: {platform: event, event_type: timer.finished, event_data: {entity_id: timer.coverprot_off_reset}}
    action: {service: homeassistant.turn_on, data: {entity_id: group.coverprot_automations}}


group:

  coverprot_automations:
    all: true
    entities:
      - automation.coverprot_wind_active_on
      - automation.coverprot_wind_active_off
      - automation.coverprot_rain_active_on
      - automation.coverprot_rain_active_off
      - automation.coverprot_wind_execute
      - automation.coverprot_rain_execute


homeassistant:

  customize:

    group.coverprot_automations:
      friendly_name: Markisenschutz autom.
      icon: mdi:home-automation
    input_boolean.coverprot_wind_active:
      friendly_name: Markisenschutz Wind aktiv
      icon: mdi:weather-windy
    input_boolean.coverprot_rain_active:
      friendly_name: Markisenschutz Regen aktiv
      icon: mdi:weather-rainy
    automation.coverprot_wind_active_on:
      friendly_name: Markisenschutz Wind ein bei Bedarf
    automation.coverprot_wind_active_off:
      friendly_name: Markisenschutz Wind aus bei Ruhe
    automation.coverprot_rain_active_on:
      friendly_name: Markisenschutz Regen ein bei Bedarf
    automation.coverprot_rain_active_off:
      friendly_name: Markisenschutz Regen aus bei Ruhe
    automation.coverprot_wind_execute:
      friendly_name: Markisen einf. wenn Windschutz aktiv
    automation.coverprot_rain_execute:
      friendly_name: Markisen einf. wenn Regenschutz aktiv
    timer.coverprot_off_reset:
      friendly_name: Markisenschutz erneut ein
    automation.coverprot_off_timer_start:
      friendly_name: Markisenschutz Timer starten
    automation.coverprot_off_timer_cancel:
      friendly_name: Markisenschutz Timer abbr.
    automation.coverprot_off_timer_expired:
      friendly_name: Markisenschutz erneut ein
