input_boolean:

  sunprot_eastface_active:
    icon: mdi:weather-sunny

  sunprot_southface_active:
    icon: mdi:weather-sunny

  sunprot_westface_active:
    icon: mdi:weather-sunny


automation:

  - alias: sunprot_eastface_active_on
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_sun_east, above: 80, for: { minutes: 20 } }
    action: { service: input_boolean.turn_on, data: { entity_id: input_boolean.sunprot_eastface_active } }
  - alias: sunprot_eastface_active_off
    trigger:
      - { platform: numeric_state, entity_id: sensor.wettersensor_sun_east, below: 50, for: { minutes: 20 } }
      - { platform: sun, event: sunset, offset: "-00:30:00" }
    action: { service: input_boolean.turn_off, data: { entity_id: input_boolean.sunprot_eastface_active } }

  - alias: sunprot_southface_active_on
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_sun_south, above: 80, for: { minutes: 20 } }
    action: { service: input_boolean.turn_on, data: { entity_id: input_boolean.sunprot_southface_active } }
  - alias: sunprot_southface_active_off
    trigger:
      - { platform: numeric_state, entity_id: sensor.wettersensor_sun_south, below: 50, for: { minutes: 20 } }
      - { platform: sun, event: sunset, offset: "-00:30:00" }
    action: { service: input_boolean.turn_off, data: { entity_id: input_boolean.sunprot_southface_active } }

  - alias: sunprot_westface_active_on
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_sun_west, above: 80, for: { minutes: 20 } }
    action: { service: input_boolean.turn_on, data: { entity_id: input_boolean.sunprot_westface_active } }
  - alias: sunprot_westface_active_off
    trigger:
      - { platform: numeric_state, entity_id: sensor.wettersensor_sun_west, below: 50, for: { minutes: 20 } }
      - { platform: sun, event: sunset, offset: "-00:30:00" }
    action: { service: input_boolean.turn_off, data: { entity_id: input_boolean.sunprot_westface_active } }

  - alias: sunprot_update_covers
    trigger:
      - { platform: state, entity_id: input_boolean.sunprot_eastface_active }
      - { platform: state, entity_id: input_boolean.sunprot_southface_active }
      - { platform: state, entity_id: input_boolean.sunprot_westface_active }
      - { platform: time_pattern, minutes: /15, seconds: 0 }
    condition:
      - { condition: time, after: '08:00:00' }
      - { condition: sun, before: sunset }
    action:
      - service: script.turn_on
        entity_id: script.sunprot_update_covers


script:

  sunprot_update_covers:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "daytime" }


group:

  sunprot_automations:
    all: true
    entities:
      - automation.sunprot_eastface_active_on
      - automation.sunprot_eastface_active_off
      - automation.sunprot_southface_active_on
      - automation.sunprot_southface_active_off
      - automation.sunprot_westface_active_on
      - automation.sunprot_westface_active_off
      - automation.sunprot_update_covers


history_graph:

  sonnenschutz:
    name: Sonnenschutz
    entities:
      - sensor.wettersensor_temperature
      - sensor.wettersensor_sun_east
      - input_boolean.sunprot_eastface_active
      - sensor.wettersensor_sun_south
      - input_boolean.sunprot_southface_active
      - sensor.wettersensor_sun_west
      - input_boolean.sunprot_westface_active
    hours_to_show: 72
    refresh: 60


homeassistant:

  customize:

    group.sunprot_automations:
      friendly_name: Sonnenschutz autom.
      icon: mdi:home-automation

    input_boolean.sunprot_eastface_active:
      friendly_name: Sonnenschutz nötig Ostseite
    automation.sunprot_eastface_active_on:
      friendly_name: Sonnenschutz nötig Ostseite einschalten
    automation.sunprot_eastface_active_off:
      friendly_name: Sonnenschutz nötig Ostseite ausschalten

    input_boolean.sunprot_southface_active:
      friendly_name: Sonnenschutz nötig Südseite
    automation.sunprot_southface_active_on:
      friendly_name: Sonnenschutz nötig Südseite einschalten
    automation.sunprot_southface_active_off:
      friendly_name: Sonnenschutz nötig Südseite ausschalten

    input_boolean.sunprot_westface_active:
      friendly_name: Sonnenschutz nötig Westseite
    automation.sunprot_westface_active_on:
      friendly_name: Sonnenschutz nötig Westseite einschalten
    automation.sunprot_westface_active_off:
      friendly_name: Sonnenschutz nötig Westseite ausschalten

    automation.sunprot_update_covers:
      friendly_name: Beschattung jetzt aktualisieren
    script.sunprot_update_covers:
      friendly_name: Beschattung jetzt aktualisieren
      icon: mdi:home-automation
      can_cancel: false
