homeassistant:

  customize:
  
    # EG
    group.shutters_eg:
      friendly_name: Verdunkelung EG
    cover.cov_wohnzimmer_sitzfenster_cover:
      friendly_name: Wohnzimmer Sitzfenster
    sensor.cover_lift_pos_wohnzimmer_sitzfenster:
      friendly_name: Wohnzimmer Sitzfenster
    cover.cov_wohnzimmer_terrassentur_cover:
      friendly_name: Wohnzimmer Terrassentür
    sensor.cover_lift_pos_wohnzimmer_terrassentur:
      friendly_name: Wohnzimmer Terrassentür
    cover.cov_terrasse_markise_cover:
      friendly_name: Terrasse Markise
    sensor.cover_lift_pos_terrasse_markise:
      friendly_name: Terrasse Markise
    cover.cov_wintergarten_markise_cover:
      friendly_name: Wintergarten Markise
    sensor.cover_lift_pos_wintergarten_markise:
      friendly_name: Wintergarten Markise
    cover.cov_kuche_terrassentur_cover:
      friendly_name: Küche Terrassentür
    sensor.cover_lift_pos_kuche_terrassentur:
      friendly_name: Küche Terrassentür
    cover.cov_kuche_fenster_cover:
      friendly_name: Küche Fenster
    sensor.cover_lift_pos_kuche_fenster:
      friendly_name: Küche Fenster
    cover.cov_windfang_cover:
      friendly_name: Windfang
    sensor.cover_lift_pos_windfang:
      friendly_name: Windfang

    # OG
    group.shutters_og:
      friendly_name: Verdunkelung OG
    cover.cov_florian_cover:
      friendly_name: Florian
    sensor.cover_lift_pos_florian:
      friendly_name: Florian
    cover.cov_jonathan_links_cover:
      friendly_name: Jonathan links
    sensor.cover_lift_pos_jonathan_links:
      friendly_name: Jonathan links
    cover.cov_jonathan_rechts_cover:
      friendly_name: Jonathan rechts
    sensor.cover_lift_pos_jonathan_rechts:
      friendly_name: Jonathan rechts
    cover.cov_schlafzimmer_cover:
      friendly_name: Schlafzimmer
    sensor.cover_lift_pos_schlafzimmer:
      friendly_name: Schlafzimmer
    cover.cov_bad_og_cover:
      friendly_name: Bad OG
    sensor.cover_lift_pos_bad_og:
      friendly_name: Bad OG
    cover.cov_flur_og_cover:
      friendly_name: Flur OG
    sensor.cover_lift_pos_flur_og:
      friendly_name: Flur OG

    # DG
    group.shutters_dg:
      friendly_name: Verdunkelung DG
    cover.cov_studio_dg_links_cover:
      friendly_name: Studio DG links
    sensor.cover_lift_pos_studio_dg_links:
      friendly_name: Studio DG links
    cover.cov_studio_dg_rechts_cover:
      friendly_name: Studio DG rechts
    sensor.cover_lift_pos_studio_dg_rechts:
      friendly_name: Studio DG rechts
    cover.cov_dachfenster_gross_cover:
      friendly_name: Dachfenster groß
    sensor.cover_lift_pos_dachfenster_gross:
      friendly_name: Dachfenster groß
    cover.cov_bad_dg_cover:
      friendly_name: Bad DG
    sensor.cover_lift_pos_bad_dg:
      friendly_name: Bad DG


input_boolean:

  covers_include_kuechentuer_in_automations:
    name: Raffstore Küchentür autom. steuern
    initial: on


group:

  shutters_eg:
    entities:
      - cover.cov_wohnzimmer_sitzfenster_cover
      - cover.cov_kuche_terrassentur_cover
      - cover.cov_kuche_fenster_cover
      - cover.cov_windfang_cover

  shutters_og:
    entities:
      - cover.cov_florian_cover
      - cover.cov_jonathan_links_cover
      - cover.cov_jonathan_rechts_cover
      - cover.cov_schlafzimmer_cover
      - cover.cov_bad_og_cover
      - cover.cov_flur_og_cover

  shutters_dg:
    entities:
      - cover.cov_studio_dg_links_cover
      - cover.cov_studio_dg_rechts_cover
      - cover.cov_dachfenster_gross_cover
      - cover.cov_bad_dg_cover

automation:
  - alias: cov_wohnzimmer_terrassentur_add
    trigger: { platform: state, entity_id: binary_sensor.aqara_winsens_terrassentur_contact, to: 'off' }
    action: { service: group.set, data: { object_id: shutters_eg, entities: [ cover.cov_wohnzimmer_sitzfenster_cover, cover.cov_wohnzimmer_terrassentur_cover, cover.cov_kuche_terrassentur_cover, cover.cov_kuche_fenster_cover, cover.cov_windfang_cover ]}}
  - alias: cov_wohnzimmer_terrassentur_remove
    trigger: { platform: state, entity_id: binary_sensor.aqara_winsens_terrassentur_contact, to: 'on' }
    action: { service: group.set, data: { object_id: shutters_eg, entities: [ cover.cov_wohnzimmer_sitzfenster_cover, cover.cov_kuche_terrassentur_cover, cover.cov_kuche_fenster_cover, cover.cov_windfang_cover ]}}
