script:
  coversatnight_covers_down:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "nighttime" }
  coversatnight_covers_down_eg:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "nighttime", "level": "eg" }
  coversatnight_covers_down_og:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "nighttime", "level": "og" }
  coversatnight_covers_down_dg:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "nighttime", "level": "dg" }
  coversatnight_covers_down_simulation:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "nighttime-simulation" }
  coversatnight_covers_up:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "morning" }
  coversatnight_covers_up_eg:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "morning", "level": "eg" }
  coversatnight_covers_up_og:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "morning", "level": "og" }
  coversatnight_covers_up_dg:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "morning", "level": "dg" }
  coversatnight_covers_up_simulation:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "morning-simulation" }


homeassistant:
  customize:
    script.coversatnight_covers_up:
      friendly_name: Raffstore jetzt hoch (alle)
    script.coversatnight_covers_up_eg:
      friendly_name: Raffstore jetzt hoch (nur EG)
    script.coversatnight_covers_up_og:
      friendly_name: Raffstore jetzt hoch (nur OG)
    script.coversatnight_covers_up_dg:
      friendly_name: Raffstore jetzt hoch (nur DG)
    script.coversatnight_covers_up_simulation:
      friendly_name: Raffstore jetzt hoch (Simulation)
    script.coversatnight_covers_down:
      friendly_name: Raffstore jetzt runter (alle)
    script.coversatnight_covers_down_eg:
      friendly_name: Raffstore jetzt runter (nur EG)
    script.coversatnight_covers_down_og:
      friendly_name: Raffstore jetzt runter (nur OG)
    script.coversatnight_covers_down_dg:
      friendly_name: Raffstore jetzt runter (nur DG)
    script.coversatnight_covers_down_simulation:
      friendly_name: Raffstore jetzt runter (Simulation)
  customize_glob:
    "script.coversatnight_covers_*":
      icon: mdi:home-automation
      can_cancel: false
