automation:

  - alias: coversatnight_down_at_dusk
    trigger:
      - platform: numeric_state
        entity_id: sensor.wettersensor_daylight
        below: '500'
        for:
          minutes: 10
      - platform: time
        minutes: /30
        seconds: 0
    condition:
      - condition: numeric_state
        entity_id: sensor.wettersensor_daylight
        below: '500'
      - condition: time
        after: '17:00:00'
        before: '04:00:00'
    action:
      - service: script.turn_on
        entity_id: script.coversatnight_covers_down

  - alias: coversatnight_up_in_the_morning
    trigger:
      platform: time
      at: '08:00:00'
    action:
      - delay: '00:{{ (range(0, 59)|random|int) }}:00'
      - service: script.turn_on
        entity_id: script.coversatnight_covers_up
      - delay: '00:05:00'
      - service: script.turn_on
        entity_id: script.coversatnight_covers_up
      - delay: '00:05:00'
      - service: script.turn_on
        entity_id: script.coversatnight_covers_up


script:

  coversatnight_covers_down:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "nighttime" }

  coversatnight_covers_up:
    sequence:
      - service: python_script.covers_ensure_state
        data: { "situation": "morning" }


group:

  coversatnight:
    control: hidden
    entities:
      - script.coversatnight_covers_down
      - script.coversatnight_covers_up

  coversatnight_automations:
    entities:
      - automation.coversatnight_down_at_dusk
      - automation.coversatnight_up_in_the_morning


homeassistant:

  customize:

    group.coversatnight:
      friendly_name: Raffstore nachts
    group.coversatnight_automations:
      friendly_name: Raffstore nachts autom.
      icon: mdi:home-automation
    automation.coversatnight_down_at_dusk:
      friendly_name: Raffstore abends autom. runter
    automation.coversatnight_up_in_the_morning:
      friendly_name: Raffstore morgens autom. rauf
    script.coversatnight_covers_down:
      friendly_name: Raffstore jetzt runterfahren
    script.coversatnight_covers_up:
      friendly_name: Raffstore jetzt hochfahren

  customize_glob:

    "script.coversatnight_covers_*":
      icon: mdi:home-automation
      can_cancel: false
