homeassistant:

  customize:
  
    # EG
    group.shutters_eg:
      friendly_name: Verdunkelung EG
    cover.f1_cov_wohnzimmer_sitzfenster_cover:
      friendly_name: Wohnzimmer Sitzfenster
    sensor.liftpos_f1_cov_wohnzimmer_sitzfenster:
      friendly_name: Wohnzimmer Sitzfenster
    cover.f1_cov_wohnzimmer_terrassentur_cover:
      friendly_name: Wohnzimmer Terrassentür
    sensor.liftpos_f1_cov_wohnzimmer_terrassentur:
      friendly_name: Wohnzimmer Terrassentür
    cover.f1_cov_terrasse_markise_cover:
      friendly_name: Terrasse Markise
    sensor.liftpos_f1_cov_terrasse_markise:
      friendly_name: Terrasse Markise
    cover.f1_cov_wintergarten_markise_cover:
      friendly_name: Wintergarten Markise
    sensor.liftpos_f1_cov_wintergarten_markise:
      friendly_name: Wintergarten Markise
    cover.f1_cov_kuche_terrassentur_cover:
      friendly_name: Küche Terrassentür
    sensor.liftpos_f1_cov_kuche_terrassentur:
      friendly_name: Küche Terrassentür
    cover.f1_cov_kuche_fenster_cover:
      friendly_name: Küche Fenster
    sensor.liftpos_f1_cov_kuche_fenster:
      friendly_name: Küche Fenster
    cover.f1_cov_windfang_cover:
      friendly_name: Windfang
    sensor.liftpos_f1_cov_windfang:
      friendly_name: Windfang

    # OG
    group.shutters_og:
      friendly_name: Verdunkelung OG
    cover.f2_cov_florian_cover:
      friendly_name: Florian
    sensor.liftpos_f2_cov_florian:
      friendly_name: Florian
    cover.f2_cov_jonathan_links_cover:
      friendly_name: Jonathan links
    sensor.liftpos_f2_cov_jonathan_links:
      friendly_name: Jonathan links
    cover.f2_cov_jonathan_rechts_cover:
      friendly_name: Jonathan rechts
    sensor.liftpos_f2_cov_jonathan_rechts:
      friendly_name: Jonathan rechts
    cover.f2_cov_schlafzimmer_cover:
      friendly_name: Schlafzimmer
    sensor.liftpos_f2_cov_schlafzimmer:
      friendly_name: Schlafzimmer
    cover.f2_cov_bad_cover:
      friendly_name: Bad OG
    sensor.liftpos_f2_cov_bad:
      friendly_name: Bad OG
    cover.f2_cov_flur_cover:
      friendly_name: Flur OG
    sensor.liftpos_f2_cov_flur:
      friendly_name: Flur OG

    # DG
    group.shutters_dg:
      friendly_name: Verdunkelung DG
    cover.f3_cov_studio_links_cover:
      friendly_name: Studio DG links
    sensor.liftpos_f3_cov_studio_links:
      friendly_name: Studio DG links
    cover.f3_cov_studio_rechts_cover:
      friendly_name: Studio DG rechts
    sensor.liftpos_f3_cov_studio_rechts:
      friendly_name: Studio DG rechts
    cover.f3_cov_dachfenster_gross_cover:
      friendly_name: Dachfenster groß innen
    sensor.liftpos_f3_cov_dachfenster_gross:
      friendly_name: Dachfenster groß innen
    cover.f3_cov_dachfenster_gross_aussen_cover:
      friendly_name: Dachfenster groß Markise
    sensor.liftpos_f3_cov_dachfenster_gross_aussen:
      friendly_name: Dachfenster groß Markise
    cover.f3_cov_bad_cover:
      friendly_name: Bad DG
    sensor.liftpos_f3_cov_bad:
      friendly_name: Bad DG


input_boolean:

  covers_include_kuechentuer_in_automations:
    name: Raffstore Küchentür autom. steuern
    initial: on


group:

  shutters_eg:
    entities:
      - cover.f1_cov_wohnzimmer_sitzfenster_cover
      - cover.f1_cov_kuche_terrassentur_cover
      - cover.f1_cov_kuche_fenster_cover
      - cover.f1_cov_windfang_cover

  shutters_og:
    entities:
      - cover.f2_cov_florian_cover
      - cover.f2_cov_jonathan_links_cover
      - cover.f2_cov_jonathan_rechts_cover
      - cover.f2_cov_schlafzimmer_cover
      - cover.f2_cov_bad_cover
      - cover.f2_cov_flur_cover

  shutters_dg:
    entities:
      - cover.f3_cov_studio_links_cover
      - cover.f3_cov_studio_rechts_cover
      - cover.f3_cov_dachfenster_gross_cover
      - cover.f3_cov_dachfenster_gross_aussen_cover
      - cover.f3_cov_bad_cover

automation:
  - alias: f1_cov_wohnzimmer_terrassentur_add
    trigger:
      - { platform: state, entity_id: binary_sensor.f1_senwin_terrassentur_contact, from: 'on', to: 'off' }
      - { platform: time_pattern, minutes: 0 }
    condition: { condition: state, entity_id: binary_sensor.f1_senwin_terrassentur_contact, state: 'off' }
    action: { service: group.set, data: { object_id: shutters_eg, entities: [ cover.f1_cov_wohnzimmer_sitzfenster_cover, cover.f1_cov_wohnzimmer_terrassentur_cover, cover.f1_cov_kuche_terrassentur_cover, cover.f1_cov_kuche_fenster_cover, cover.f1_cov_windfang_cover ]}}
  - alias: f1_cov_wohnzimmer_terrassentur_remove
    trigger:
      - { platform: state, entity_id: binary_sensor.f1_senwin_terrassentur_contact, from: 'off', to: 'on' }
      - { platform: time_pattern, minutes: 0 }
    condition: { condition: state, entity_id: binary_sensor.f1_senwin_terrassentur_contact, state: 'on' }
    action: { service: group.set, data: { object_id: shutters_eg, entities: [ cover.f1_cov_wohnzimmer_sitzfenster_cover, cover.f1_cov_kuche_terrassentur_cover, cover.f1_cov_kuche_fenster_cover, cover.f1_cov_windfang_cover ]}}
