input_boolean:

  coverprot_wind_active:


automation:

  - alias: coverprot_wind_active_on
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_wind_speed_gusts, above: 35 }
    action: { service: input_boolean.turn_on, data: { entity_id: input_boolean.coverprot_wind_active } }
  - alias: coverprot_wind_active_off
    trigger: { platform: numeric_state, entity_id: sensor.wettersensor_wind_speed_gusts, below: 30, for: { minutes: 10 } }
    action: { service: input_boolean.turn_off, data: { entity_id: input_boolean.coverprot_wind_active } }

  - alias: coverprot_turn_on
    trigger:
      - { platform: state, entity_id: input_boolean.coverprot_wind_active, to: 'on' }
      - { platform: time, minutes: /2, seconds: 0 }
    condition:
      - { condition: state, entity_id: input_boolean.coverprot_wind_active, state: 'on' }
    action:
      - service: cover.open_cover
        entity_id: cover.cov_wintergarten_markise
      - service: cover.open_cover
        entity_id: cover.cov_dachfenster_gross


group:

  coverprot:
    control: hidden
    entities:
      - sensor.wettersensor_wind_speed_gusts
      - input_boolean.coverprot_wind_active

  coverprot_automations:
    entities:
      - automation.coverprot_wind_active_on
      - automation.coverprot_wind_active_off
      - automation.coverprot_turn_on


homeassistant:

  customize:

    group.coverprot:
      friendly_name: Markisenschutz
    group.coverprot_automations:
      friendly_name: Markisenschutz autom.
      icon: mdi:home-automation
    input_boolean.coverprot_wind_active:
      friendly_name: Markisenschutz nötig
      icon: mdi:weather-windy
    automation.coverprot_wind_active_on:
      friendly_name: Markisenschutz nötig einschalten
    automation.coverprot_wind_active_off:
      friendly_name: Markisenschutz nötig einschalten
    automation.coverprot_turn_on:
      friendly_name: Markisen einfahren wenn nötig
