automation:

  - alias: covers_down_at_dusk
    trigger:
      - platform: numeric_state
        entity_id: sensor.wettersensor_daylight
        below: '500'
        for:
          minutes: 10
      - platform: time
        minutes: /30
        seconds: 0
    condition:
      - condition: numeric_state
        entity_id: sensor.wettersensor_daylight
        below: '500'
      - condition: time
        after: '17:00:00'
        before: '04:00:00'
    action:
      - service: python_script.covers_ensure_state
        data: { "target_state": "nighttime" }

  - alias: covers_up_in_the_morning
    trigger:
      platform: time
      at: '08:00:00'
    action:
      - delay: '00:{{ (range(0, 59)|random|int) }}:00'
      - service: python_script.covers_ensure_state
        data: { "target_state": "morning" }
      - delay: '00:05:00'
      - service: python_script.covers_ensure_state
        data: { "target_state": "morning" }
      - delay: '00:05:00'
      - service: python_script.covers_ensure_state
        data: { "target_state": "morning" }



homeassistant:

  customize:

    automation.covers_down_at_dusk:
      friendly_name: Raffstore abends runter
    automation.covers_up_in_the_morning:
      friendly_name: Raffstore morgens rauf
    automation.covers_up_during_daytime:
      friendly_name: Raffstore tagsüber oben halten
