homeassistant:

  customize:
  
    # EG
    cover.cov_wohnzimmer_sitzfenster:
      friendly_name: Wohnzimmer Sitzfenster
    sensor.cover_lift_pos_cov_wohnzimmer_sitzfenster:
      friendly_name: Wohnzimmer Sitzfenster
    cover.cov_wohnzimmer_terrassentur:
      friendly_name: Wohnzimmer Terrassentür
    sensor.cover_lift_pos_cov_wohnzimmer_terrassentur:
      friendly_name: Wohnzimmer Terrassentür
    cover.cov_wintergarten_markise:
      friendly_name: Wintergarten Markise
    sensor.cover_lift_pos_cov_wintergarten_markise:
      friendly_name: Wintergarten Markise
    cover.cov_kuche_terrassentur:
      friendly_name: Küche Terrassentür
    sensor.cover_lift_pos_cov_kuche_terrassentur:
      friendly_name: Küche Terrassentür
    cover.cov_kuche_fenster:
      friendly_name: Küche Fenster
    sensor.cover_lift_pos_cov_kuche_fenster:
      friendly_name: Küche Fenster
    cover.cov_windfang:
      friendly_name: Windfang
    sensor.cover_lift_pos_cov_windfang:
      friendly_name: Windfang

    # OG
    cover.cov_florian:
      friendly_name: Florian
    sensor.cover_lift_pos_cov_florian:
      friendly_name: Florian
    cover.cov_jonathan_links:
      friendly_name: Jonathan links
    sensor.cover_lift_pos_cov_jonathan_links:
      friendly_name: Jonathan links
    cover.cov_jonathan_rechts:
      friendly_name: Jonathan rechts
    sensor.cover_lift_pos_cov_jonathan_rechts:
      friendly_name: Jonathan rechts
    cover.cov_schlafzimmer:
      friendly_name: Schlafzimmer
    sensor.cover_lift_pos_cov_schlafzimmer:
      friendly_name: Schlafzimmer
    cover.cov_bad_og:
      friendly_name: Bad OG
    sensor.cover_lift_pos_cov_bad_og:
      friendly_name: Bad OG
    cover.cov_flur_og:
      friendly_name: Flur OG
    sensor.cover_lift_pos_cov_flur_og:
      friendly_name: Flur OG

    # DG
    cover.cov_studio_dg_links:
      friendly_name: Studio DG links
    sensor.cover_lift_pos_cov_studio_dg_links:
      friendly_name: Studio DG links
    cover.cov_studio_dg_rechts:
      friendly_name: Studio DG rechts
    sensor.cover_lift_pos_cov_studio_dg_rechts:
      friendly_name: Studio DG rechts
    cover.cov_dachfenster_gross:
      friendly_name: Dachfenster groß
    sensor.cover_lift_pos_cov_dachfenster_gross:
      friendly_name: Dachfenster groß
    cover.cov_bad_dg:
      friendly_name: Bad DG
    sensor.cover_lift_pos_cov_bad_dg:
      friendly_name: Bad DG

    history_graph.sonnenschutz:
      friendly_name: Sonnenschutz Historie

    history_graph.covers_lift_position:
      friendly_name: Beschattung Position


group:

  covers_on_default_view:
    name: Beschattung
    control: hidden
    entities:
      - input_boolean.covers_include_terrassentuer_in_automations
      - input_boolean.covers_include_kuechentuer_in_automations
      - group.sunprot_automations
      - input_boolean.sunprot_eastface_active
      - input_boolean.sunprot_southface_active
      - input_boolean.sunprot_westface_active
      - group.coversatnight_automations
      - script.coversatnight_covers_down
      - script.coversatnight_covers_up
      - group.coverprot_automations
      - input_boolean.coverprot_wind_active

  covers_tab:
    view: yes
    name: Beschattung
    entities:
      - group.covers_all
      - group.sunprot
      - history_graph.sonnenschutz
      - group.sunprot_automations
      - group.coversatnight
      - group.coversatnight_automations
      - group.coverprot
      - group.coverprot_automations
      - history_graph.covers_lift_position

  covers_all:
    name: Beschattung
    control: hidden
    entities:
      - input_boolean.covers_include_terrassentuer_in_automations
      - input_boolean.covers_include_kuechentuer_in_automations
      - cover.cov_wohnzimmer_sitzfenster
      - cover.cov_wohnzimmer_terrassentur
      - cover.cov_wintergarten_markise
      - cover.cov_kuche_terrassentur
      - cover.cov_kuche_fenster
      - cover.cov_windfang
      - cover.cov_florian
      - cover.cov_jonathan_links
      - cover.cov_jonathan_rechts
      - cover.cov_schlafzimmer
      - cover.cov_bad_og
      - cover.cov_flur_og
      - cover.cov_studio_dg_links
      - cover.cov_studio_dg_rechts
      - cover.cov_dachfenster_gross
      - cover.cov_bad_dg


input_boolean:

  covers_include_terrassentuer_in_automations:
    name: Raffstore Terrassentür autom. steuern
    initial: off

  covers_include_kuechentuer_in_automations:
    name: Raffstore Küchentür autom. steuern
    initial: on
