netatmo:
  username: !secret netatmo_username
  password: !secret netatmo_password
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  discovery: false

sensor:
  - platform: netatmo_public
    areas:
      - name: Netatmo Public Oberursel Nord
        lat_ne: 50.230
        lon_ne:  8.581
        lat_sw: 50.205
        lon_sw:  8.546
        monitored_conditions:
          - temperature
          - pressure
          - humidity
          - rain
          - windstrength
          - guststrength

group:
  wetter_lokal_netatmo_public:
    name: Wetter lokal Netatmo Public
    entities:
      - sensor.netatmo_public_oberursel_nord_temperature
      - sensor.netatmo_public_oberursel_nord_pressure
      - sensor.netatmo_public_oberursel_nord_humidity
      - sensor.netatmo_public_oberursel_nord_rain
      - sensor.netatmo_public_oberursel_nord_wind_strength
      - sensor.netatmo_public_oberursel_nord_gust_strength

history_graph:
  wetter_lokal_netatmo_public:
    name: Wetter lokal Netatmo Public
    entities:
      - sensor.netatmo_public_oberursel_nord_temperature
      - sensor.netatmo_public_oberursel_nord_pressure
      - sensor.netatmo_public_oberursel_nord_humidity
      - sensor.netatmo_public_oberursel_nord_rain
      - sensor.netatmo_public_oberursel_nord_wind_strength
      - sensor.netatmo_public_oberursel_nord_gust_strength
    hours_to_show: 72
    refresh: 60
