netatmo:
  username: !secret netatmo_username
  password: !secret netatmo_password
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  discovery: false

sensor:
  - platform: netatmo
    areas:
      - name: Netatmo Public Oberursel Nord
        lat_ne: 50.230
        lon_ne:  8.581
        lat_sw: 50.205
        lon_sw:  8.546
