automation:

  - alias: sonos_bad_play
    trigger: { platform: state, entity_id: sensor.philips_fb_action, to: on-hold }
    action: { service: media_player.media_play, entity_id: media_player.bad }
  - alias: sonos_bad_pause
    trigger: { platform: state, entity_id: sensor.philips_fb_action, to: off-hold  }
    action: { service: media_player.media_pause, entity_id: media_player.bad }
  - alias: sonos_bad_volume_up
    trigger: { platform: state, entity_id: sensor.philips_fb_action, to: on-press }
    action: { service: media_player.volume_up, entity_id: media_player.bad }
  - alias: sonos_bad_volume_down
    trigger: { platform: state, entity_id: sensor.philips_fb_action, to: off-press }
    action: { service: media_player.volume_down, entity_id: media_player.bad }
  - alias: sonos_bad_next_track
    trigger: { platform: state, entity_id: sensor.philips_fb_action, to: up-press }
    action: { service: media_player.media_next_track, entity_id: media_player.bad }
  - alias: sonos_bad_previous_track
    trigger: { platform: state, entity_id: sensor.philips_fb_action, to: down-press }
    action: { service: media_player.media_previous_track, entity_id: media_player.bad }
