automation:

  - alias: sonos_bad_play_pause
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: toggle}
    action: {entity_id: media_player.bad, service: media_player.media_play_pause}
  - alias: sonos_bad_play
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: up}
    action: {entity_id: media_player.bad, service: media_player.media_play}
  - alias: sonos_bad_pause
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: toggle_hold}
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: down}
    action: {entity_id: media_player.bad, service: media_player.media_pause}
  - alias: sonos_bad_volume_up
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: brightness_up_click}
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: 'on'}
    action: {entity_id: media_player.bad, service: media_player.volume_up}
  - alias: sonos_bad_volume_down
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: brightness_down_click}
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: 'off'}
    action: {entity_id: media_player.bad, service: media_player.volume_down}
  - alias: sonos_bad_previous_track
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: arrow_left_click}
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: select_0}
    action: {entity_id: media_player.bad, service: media_player.media_previous_track}
  - alias: sonos_bad_next_track
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: arrow_right_click}
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: select_1}
    action: {entity_id: media_player.bad, service: media_player.media_next_track}
  - alias: sonos_bad_spotify_playlist_0
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: brightness_up_hold}
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: select_2}
    action:
      - {entity_id: media_player.bad, service: media_player.shuffle_set, data: {shuffle: true}}
      - {entity_id: media_player.bad, service: media_player.select_source, data: {source: 'Sommerhits'}}
  - alias: sonos_bad_spotify_playlist_1
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: arrow_right_hold}
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: select_3}
    action:
      - {entity_id: media_player.bad, service: media_player.shuffle_set, data: {shuffle: true}}
      - {entity_id: media_player.bad, service: media_player.select_source, data: {source: 'Stimmungsmacher'}}
  - alias: sonos_bad_spotify_playlist_2
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: brightness_down_hold}
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: select_4}
    action:
      - {entity_id: media_player.bad, service: media_player.shuffle_set, data: {shuffle: true}}
      - {entity_id: media_player.bad, service: media_player.select_source, data: {source: 'Feelgood Indie'}}
  - alias: sonos_bad_spotify_playlist_3
    trigger:
      - {platform: state, entity_id: sensor.f2_but_bad_dusche_action, to: arrow_left_hold}
      - {platform: state, entity_id: sensor.f2_but_bad_1_action, to: select_5}
    action:
      - {entity_id: media_player.bad, service: media_player.shuffle_set, data: {shuffle: true}}
      - {entity_id: media_player.bad, service: media_player.select_source, data: {source: 'Swag!'}}
