sensor:
  - platform: yr
    name: yr_current
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: yr
    name: yr_forecast_24h
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature



group:

  weather_current:
    entities:
      - sensor.wettersensor_is_raining
      - sensor.netatmo_public_oberursel_nord_rain
      - sensor.yr_current_symbol
      - sensor.wettersensor_temperature
      - sensor.heizung_aussen_temperatur
      - sensor.netatmo_public_oberursel_nord_temperature
      - sensor.yr_current_temperature
      - sensor.netatmo_public_oberursel_nord_humidity
      - sensor.yr_current_humidity
      - sensor.pressure_38
      - sensor.pressure_41
      - sensor.netatmo_public_oberursel_nord_pressure
      - sensor.yr_current_pressure
      - sensor.wettersensor_wind_speed
      - sensor.netatmo_public_oberursel_nord_wind_strength
      - sensor.netatmo_public_oberursel_nord_gust_strength
      - sensor.yr_current_wind_speed

  weather_forecast:
    entities:
      - sensor.yr_forecast_24h_symbol
      - sensor.yr_forecast_24h_temperature

  weather_inside:
    entities:
      - sensor.comfoairq_inside_temperature
      - sensor.temperature_39
      - sensor.temperature_37
      - sensor.comfoairq_inside_humidity
      - sensor.humidity_40
      - sensor.humidity_36
