##############################
## lokaler Wettersensor
##############################

sensor:
  - platform: rest
    name: Wettersensor
    resource: http://192.168.0.11/
    json_attributes:
      - readAgeMs
      - tempC
      - eastKlx
      - southKlx
      - westKlx
      - daylightLx
      - isDark
      - windMs
      - windGustsMs
      - isRain
      - covProt1IsAct
      - covProt2IsAct
    scan_interval: 60
  - platform: template
    sensors:
      wettersensor_reading_age:
        value_template: '{{ states.sensor.wettersensor.attributes["readAgeMs"] }}'
        unit_of_measurement: "ms"
      wettersensor_temperature:
        value_template: '{{ states.sensor.wettersensor.attributes["tempC"] }}'
        unit_of_measurement: "°C"
      wettersensor_sun_east:
        value_template: '{{ states.sensor.wettersensor.attributes["eastKlx"] }}'
        unit_of_measurement: "klx"
      wettersensor_sun_south:
        value_template: '{{ states.sensor.wettersensor.attributes["southKlx"] }}'
        unit_of_measurement: "klx"
      wettersensor_sun_west:
        value_template: '{{ states.sensor.wettersensor.attributes["westKlx"] }}'
        unit_of_measurement: "klx"
      wettersensor_daylight:
        value_template: '{{ states.sensor.wettersensor.attributes["daylightLx"] }}'
        unit_of_measurement: "lx"
      wettersensor_is_dark:
        value_template: "{% if is_state_attr('sensor.wettersensor', 'isDark', 0) %} nein {% elif is_state_attr('sensor.wettersensor', 'isDark', 1) %} ja {% else %} Invalid: '{{ state_attr('sensor.wettersensor', 'isDark') }}' {% endif %}"
        icon_template: "{% if is_state_attr('sensor.wettersensor', 'isDark', 0) %} mdi:weather-sunny {% else %} mdi:weather-night {% endif %}"
      wettersensor_wind_speed:
        value_template: '{{ (states.sensor.wettersensor.attributes["windMs"] | float * 3.6) | int }}'
        unit_of_measurement: "km/h"
      wettersensor_wind_speed_gusts:
        value_template: '{{ (states.sensor.wettersensor.attributes["windGustsMs"] | float * 3.6) | int }}'
        unit_of_measurement: "km/h"
      wettersensor_is_raining:
        value_template: "{% if is_state_attr('sensor.wettersensor', 'isRain', 0) %} nein {% elif is_state_attr('sensor.wettersensor', 'isRain', 1) %} ja {% else %} Invalid: '{{ state_attr('sensor.wettersensor', 'isRain') }}' {% endif %}"
        icon_template: "{% if is_state_attr('sensor.wettersensor', 'isRain', 0) %} mdi:weather-sunny {% else %} mdi:weather-pouring {% endif %}"
      wettersensor_coverprot1_is_active:
        value_template: "{% if is_state_attr('sensor.wettersensor', 'covProt1IsAct', 0) %} nein {% elif is_state_attr('sensor.wettersensor', 'covProt1IsAct', 1) %} ja {% else %} Invalid: '{{ state_attr('sensor.wettersensor', 'covProt1IsAct') }}' {% endif %}"
        icon_template: "{% if is_state_attr('sensor.wettersensor', 'covProt1IsAct', 0) %} mdi:weather-sunny {% else %} mdi:weather-windy {% endif %}"
      wettersensor_coverprot2_is_active:
        value_template: "{% if is_state_attr('sensor.wettersensor', 'covProt2IsAct', 0) %} nein {% elif is_state_attr('sensor.wettersensor', 'covProt2IsAct', 1) %} ja {% else %} Invalid: '{{ state_attr('sensor.wettersensor', 'covProt2IsAct') }}' {% endif %}"
        icon_template: "{% if is_state_attr('sensor.wettersensor', 'covProt2IsAct', 0) %} mdi:weather-sunny {% else %} mdi:weather-windy {% endif %}"

homeassistant:
  customize:
    sensor.wettersensor_reading_age:
      friendly_name: Alter d. Messung
    sensor.wettersensor_temperature:
      friendly_name: Außentemperatur
    sensor.wettersensor_sun_east:
      friendly_name: Sonne von Osten
      device_class: illuminance
    sensor.wettersensor_sun_south:
      friendly_name: Sonne von Süden
      device_class: illuminance
    sensor.wettersensor_sun_west:
      friendly_name: Sonne von Westen
      device_class: illuminance
    sensor.wettersensor_daylight:
      friendly_name: Helligkeit
      device_class: illuminance
    sensor.wettersensor_is_dark:
      friendly_name: dunkel
    sensor.wettersensor_wind_speed:
      friendly_name: Windgeschwindigkeit
      icon: mdi:weather-windy-variant
    sensor.wettersensor_wind_speed_gusts:
      friendly_name: Böen
      icon: mdi:weather-windy
    sensor.wettersensor_is_raining:
      friendly_name: Regen
    sensor.wettersensor_coverprot1_is_active:
      friendly_name: Cover Protection 1 aktiv
    sensor.wettersensor_coverprot2_is_active:
      friendly_name: Cover Protection 2 aktiv
