####################
## ZHA
####################


homeassistant:
  customize:

    # EG
    switch.ubisys_s1_5501_00001a89_1_6:
      hidden: true  # managed by deCONZ
    binary_sensor.ubisys_s1_5501_00001a89_2:
      hidden: true  # managed by deCONZ
    switch.ubisys_s1_5501_00001a95_1_6:
      hidden: true  # managed by deCONZ
    binary_sensor.ubisys_s1_5501_00001a95_2:
      hidden: true  # managed by deCONZ

    # OG
    light.ubisys_d1r_5603_00001d41_1:
      friendly_name: Flur OG
      hidden: true  # managed by deCONZ

    # DG
    light.philips_ltw001_02481a1c_11:
      friendly_name: Studio DG
      hidden: true  # managed by deCONZ
    binary_sensor.ubisys_d1r_5603_00001d41_2:
      hidden: true  # managed by deCONZ
    binary_sensor.ubisys_d1r_5603_00001d41_3:
      hidden: true  # managed by deCONZ
